import { motion } from 'framer-motion';
import { Play, Quote, Star } from 'lucide-react';
import SectionHeading from '../components/SectionHeading';
import { testimonials } from '../data/testimonials';

export default function Testimonials() {
  return (
    <>
      <section className="pt-32 sm:pt-36"><div className="mx-auto max-w-7xl px-4 pb-14 sm:px-6 lg:px-8 lg:pb-20"><SectionHeading eyebrow="Testimonials" title="Real stories belong at the centre of a local education brand." copy="The page is ready for approved reviews, student photos and video testimonials. Until then, the content below is clearly marked as placeholder." /><div className="mt-10 grid gap-5 md:grid-cols-2">{testimonials.map((item, index) => <motion.article key={item.name} initial={{ opacity: 0, y: 18 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: index * .05 }} className="rounded-[2rem] border border-brand-100 bg-white p-7 card-shadow"><div className="flex items-center justify-between"><Quote className="text-accent-500" /><div className="flex gap-1 text-accent-500">{Array.from({ length: item.rating }).map((_, i) => <Star key={i} size={15} fill="currentColor" />)}</div></div><blockquote className="mt-6 text-lg leading-8 text-brand-950">“{item.quote}”</blockquote><div className="mt-7 flex items-center gap-3"><img src={item.image} loading="lazy" alt="" className="h-12 w-12 rounded-full object-cover" /><div><p className="font-bold">{item.name}</p><p className="text-sm text-slate-500">{item.role}</p></div></div></motion.article>)}</div></div></section>
      <section className="bg-brand-950"><div className="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8 lg:py-20"><SectionHeading eyebrow="Video testimonials" title="A space for parent and student stories on video." copy="TODO: replace these visual placeholders with hosted video thumbnails or embedded YouTube/Vimeo content after receiving final links." /><div className="mt-10 grid gap-5 md:grid-cols-3">{['A parent shares their experience', 'A student talks about exam prep', 'Tutor-student learning journey'].map((label, index) => <motion.button key={label} type="button" whileHover={{ y: -5 }} className="group relative overflow-hidden rounded-[2rem] bg-white/5 text-left"><div className={`aspect-video ${index === 1 ? 'bg-brand-800' : 'bg-brand-700'} p-5`}><div className="flex h-full items-center justify-center rounded-2xl border border-white/10 bg-black/10"><span className="grid h-14 w-14 place-items-center rounded-full bg-accent-500 text-brand-950 shadow-lg"><Play size={21} fill="currentColor" /></span></div></div><div className="p-5"><p className="font-display font-bold text-white">{label}</p><p className="mt-1 text-sm text-white/45">Video placeholder</p></div></motion.button>)}</div></div></section>
    </>
  );
}
